on: [push, pull_request, workflow_dispatch]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
    - name: checkout source repo
      uses: actions/checkout@v2

    - name: linting
      uses: alexanderdamiani/pylinter@v1.3.0
      with:
        python-root: '.'
        flake8-flags:  '--count --show-source --statistics'
        fail-on-isort: true
        skip-mypy: true

